{# G_MSA #}
{{ config(
    materialized='proplum',
    incremental_strategy='delta_upsert',
    delta_field='load_at',
    merge_keys=['g_scenario', 'g_version', 'month', 'g_entity'],
    engine='MergeTree',
    schema='DDM_ASKB',
    tags=['askb','ddm'],
    order_by='g_scenario, g_version, g_entity, month',
    partition_by = 'month'    
) }}
select G_Scenario	as	g_scenario,
    G_Versions	as	g_version,
    substring(G_Year,4,4)::UInt16	as	year,
    makeDate(year, toUInt8(substring(G_Period,6,2))*3 + toUInt8(substring(G_Period,8,2)) -3, 1) as month,
    --G_Period	as	g_period,
    G_Currency_Type	as	g_currency_type,
    G_Currency	as	g_currency,
    G_Entity	as	g_entity,
    G_Forms	as	g_forms,
    G_Adjustments	as	g_adjustments,
    G_Flows	as	g_flows,
    G_Mine	as	g_mine,
    G_Finance_Contracts	as	g_finance_contracts,
    G_Stores_List	as	g_stores_list,
    G_Appraisal_Model_Items	as	g_appraisal_model_items,
    G_Counterparty	as	g_counterparty,
    G_Counterparty_Re	as	g_counterparty_re,
    G_Cost_Elements_Cash_Flows	as	g_cost_elements_cash_flows,
    G_Project	as	g_project,
    F_UH_Accounts_Dt	as	f_uh_accounts_dt,
    F_UH_Accounts_Kt	as	f_uh_accounts_kt,
    G_Accounts	as	g_accounts,
    G_Production_Groups	as	g_production_groups,
    G_Subdivisions	as	g_subdivisions,
    G_MSA_Measures	as	g_msa_measures,
    Value	as	value,
    assumeNotNull(_time) as load_at
from {{ref('stg_askb_et_g_msa')}}